prices:
  - id: monthly
    name: "per month"
    amount: 1000
    currency: usd
    recurring: month
  - id: annually
    name: "per year"
    amount: 11000
    currency: usd
    recurring: year

plans:
  - id: network-subscription
    name: "All Network Subscription"
    prices:
      - ten
      - twenty
    included:
      - all
