services:
  live:
    cpu_count: 1
    mem_limit: 2gb
    build:
      context: ./apps/live
      dockerfile: ./Dockerfile
    env_file:
      - .env
    environment:
      - PORT=3000
      - VAR_DIR=/var/studio
      - PRIVATE_URL=http://live:3000
      - GENERATE_API_URL=http://generate:3000
      - RTMP_API_URL=http://rtmp:3000
      - RTMP_HOSTNAME=rtmp
      - RTMP_STREAM_PORT=1935
      - RTMP_UDP_RANGE=9000-9999
    ports:
      - '8080:3000'
    volumes:
      - ./tmp:/var/studio
      - ./apps/live/fixtures:/var/fixtures
      - ./apps/live/src:/app/src
  rtmp:
    cpu_count: 1
    mem_limit: 2gb
    build:
      context: ./apps/rtmp
      dockerfile: ./Dockerfile
    environment:
      - PORT=3000
      - VAR_DIR=/var/studio
      - STREAM_PORT=1935
      - UDP_RANGE=9000-9999
    env_file:
      - .env
    ports:
      - '1935:1935'
      - '8081:3000'
      - '9000-9999:9000-9999/udp'
    volumes:
      - ./apps/rtmp/src/controller.ts:/app/controller.ts  
  generate:
    build:
      context: ./apps/generate
      dockerfile: ./Dockerfile
    env_file:
      - .env
    ports:
      - '8082:3000'
    environment:
      - PORT=3000
      - VAR_DIR=/var/studio
    volumes:
      - ./apps/generate/src:/app/src
      - ./tmp/:/var/studio
    
